name: Generate license CSV
on:
  workflow_dispatch:

jobs:
  build:
    name: Generate license CSV
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the file
        shell: pwsh
        run: (Invoke-RestMethod -Method GET -Uri "https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv") | ConvertFrom-Csv | Select-Object Product_Display_Name,GUID | Sort-Object -Property 'GUID' -Unique | Export-Csv -Path "licensetable.csv" -NoTypeInformation -Force
      - name: Commit file
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . --force
          git commit -am "commit licensetable.csv file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
