name: Generate license CSV
on:
  workflow_dispatch:

jobs:
  build:
    name: Generate license CSV
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the file
        shell: pwsh
        run: .\build-licensetable.ps1
      - name: Commit file
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . --force
          git commit -am "commit file123"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
